// 图标数据
import {
  SettingOutlined,
  UserOutlined,
  DatabaseOutlined,
  KeyOutlined,
  MailOutlined,
  FileTextOutlined,
  BarChartOutlined,
  CloudOutlined,
  SafetyOutlined,
  ThunderboltOutlined,
  GlobalOutlined,
  CodeOutlined,
  MonitorOutlined,
  CloudServerOutlined,
  MobileOutlined,
  LaptopOutlined,
  HddOutlined,
  WifiOutlined,
  CameraOutlined,
  AudioOutlined,
  CarryOutOutlined,
  PrinterOutlined,
  LineChartOutlined,
  ExclamationCircleOutlined,
  CheckCircleOutlined,
  ClockCircleOutlined,
  StarOutlined,
  HeartOutlined,
  BookOutlined,
  FlagOutlined,
  AimOutlined,
  CompassOutlined,
  EnvironmentOutlined,
  SendOutlined,
  AppstoreOutlined,
  BorderOutlined,
  InboxOutlined,
  GiftOutlined,
  CarOutlined,
  ShoppingCartOutlined,
  CreditCardOutlined,
  DollarOutlined,
  PieChartOutlined,
  AreaChartOutlined,
  CalendarOutlined,
  FieldTimeOutlined,
  BellOutlined,
  SoundOutlined,
  CustomerServiceOutlined,
  VideoCameraOutlined,
  PictureOutlined,
  PlayCircleOutlined,
  CustomerServiceOutlined as MusicNoteOutlined,
  RadiusSettingOutlined,
  DesktopOutlined,
  WifiOutlined as RssOutlined,
  ReadOutlined,
  EditOutlined,
  BulbOutlined,
  TrophyOutlined,
  TrophyOutlined as MedalOutlined,
  RedEnvelopeOutlined,
  FireOutlined,
  SunOutlined,
  MoonOutlined,
  CloudOutlined as CloudRainOutlined,
  StarOutlined as SnowflakeOutlined,
  CarryOutOutlined as UmbrellaOutlined,
  DashboardOutlined,
  ThunderboltOutlined as WindPowerOutlined,
  EyeOutlined,
  SearchOutlined,
  FilterOutlined,
  ReloadOutlined,
  DownloadOutlined,
  UploadOutlined,
  ShareAltOutlined,
  CopyOutlined,
  ScissorOutlined,
  PaperClipOutlined,
  LinkOutlined,
  LockOutlined,
  UnlockOutlined,
  UserAddOutlined,
  UserSwitchOutlined,
  CrownOutlined,
  ContainerOutlined,
  BankOutlined as BuildingOutlined,
  BankOutlined,
  ShopOutlined,
  GoldOutlined,
  PushpinOutlined,
  TrademarkCircleOutlined,
  ProjectOutlined,
  RocketOutlined,
  RocketOutlined as ShipOutlined,
  CarOutlined as BikeOutlined,
  ExperimentOutlined,
  ThunderboltOutlined as BatteryTwoTone,
  ApiOutlined as PlugOneOutlined,
  PoweroffOutlined,
  ScanOutlined,
  QrcodeOutlined,
  BarcodeOutlined,
  NumberOutlined,
  UserOutlined as AtSignOutlined,
  PercentageOutlined,
  SafetyCertificateOutlined,
  BgColorsOutlined,
  HighlightOutlined,
  EditOutlined as EditTwoToneOutlined,
  FormOutlined,
  DeleteOutlined,
  LineOutlined,
  FontSizeOutlined,
  BoldOutlined,
  ItalicOutlined,
  UnderlineOutlined,
  MessageOutlined,
  OrderedListOutlined,
  LayoutOutlined,
  TableOutlined,
  ColumnWidthOutlined,
  BorderInnerOutlined,
  RadiusUprightOutlined,
  CaretUpOutlined,
  StopOutlined,
  BorderOutlined as DiamondOutlined,
  BlockOutlined,
  AppstoreOutlined as PuzzleOutlined,
  DeploymentUnitOutlined,
  ShareAltOutlined as WorkflowOutlined,
  BranchesOutlined,
  GithubOutlined,
  ChromeOutlined,
  FireOutlined as FirefoxOutlined,
  WifiOutlined as BluetoothOutlined,
  UsbOutlined,
  CustomerServiceFilled,
  FolderOutlined,
  FileOutlined,
  FileZipOutlined,
  InboxOutlined as MailInboxOutlined,
  ForwardOutlined,
  RollbackOutlined,
  HomeOutlined,
  BookFilled,
  DragOutlined,
  // 新增的图标
  ApiOutlined,
  AppstoreAddOutlined,
  ApartmentOutlined,
  TeamOutlined,
  UsergroupAddOutlined,
  NodeIndexOutlined,
  ClusterOutlined,
  SecurityScanOutlined,
  AuditOutlined,
  InsertRowAboveOutlined,
  ControlOutlined,
  FunctionOutlined,
  BugOutlined,
  ToolOutlined,
  WarningOutlined,
  InfoCircleOutlined,
  QuestionCircleOutlined,
  SmileOutlined,
  FrownOutlined,
  MehOutlined,
  InteractionOutlined,
  NotificationOutlined,
  AlertOutlined,
} from '@ant-design/icons';

import { IconOption, ColorOption, MenuItem, UrlTypeOption } from "./types";

// 头像图标选项
export const iconOptions: IconOption[] = [
  { value: "Settings", icon: SettingOutlined, label: "设置" },
  { value: "Users", icon: UserOutlined, label: "用户" },
  { value: "Database", icon: DatabaseOutlined, label: "数据库" },
  { value: "Key", icon: KeyOutlined, label: "密钥" },
  { value: "Mail", icon: MailOutlined, label: "邮件" },
  { value: "FileText", icon: FileTextOutlined, label: "文档" },
  { value: "BarChart3", icon: BarChartOutlined, label: "图表" },
  { value: "Cloud", icon: CloudOutlined, label: "云服务" },
  { value: "Shield", icon: SafetyOutlined, label: "安全" },
  { value: "Zap", icon: ThunderboltOutlined, label: "闪电" },
  { value: "Globe", icon: GlobalOutlined, label: "全球" },
  { value: "Code", icon: CodeOutlined, label: "代码" },
  { value: "Monitor", icon: MonitorOutlined, label: "监控" },
  { value: "Server", icon: CloudServerOutlined, label: "服务器" },
  { value: "Smartphone", icon: MobileOutlined, label: "手机" },
  { value: "Laptop", icon: LaptopOutlined, label: "笔记本" },
  { value: "HardDrive", icon: HddOutlined, label: "硬盘" },
  { value: "Wifi", icon: WifiOutlined, label: "网络" },
  { value: "Camera", icon: CameraOutlined, label: "相机" },
  { value: "Headphones", icon: AudioOutlined, label: "耳机" },
  { value: "Gamepad2", icon: CarryOutOutlined, label: "游戏" },
  { value: "Printer", icon: PrinterOutlined, label: "打印机" },
  { value: "Activity", icon: LineChartOutlined, label: "活动" },
  { value: "AlertCircle", icon: ExclamationCircleOutlined, label: "警告" },
  { value: "CheckCircle", icon: CheckCircleOutlined, label: "完成" },
  { value: "Clock", icon: ClockCircleOutlined, label: "时钟" },
  { value: "Star", icon: StarOutlined, label: "星星" },
  { value: "Heart", icon: HeartOutlined, label: "心形" },
  { value: "Bookmark", icon: BookOutlined, label: "书签" },
  { value: "Flag", icon: FlagOutlined, label: "旗帜" },
  { value: "Target", icon: AimOutlined, label: "目标" },
  { value: "Compass", icon: CompassOutlined, label: "指南针" },
  { value: "Map", icon: EnvironmentOutlined, label: "地图" },
  { value: "Navigation", icon: SendOutlined, label: "导航" },
  { value: "Layers", icon: AppstoreOutlined, label: "图层" },
  { value: "Grid", icon: BorderOutlined, label: "网格" },
  { value: "Box", icon: InboxOutlined, label: "盒子" },
  { value: "Package", icon: GiftOutlined, label: "包裹" },
  { value: "Truck", icon: CarOutlined, label: "卡车" },
  { value: "ShoppingCart", icon: ShoppingCartOutlined, label: "购物车" },
  { value: "CreditCard", icon: CreditCardOutlined, label: "信用卡" },
  { value: "DollarSign", icon: DollarOutlined, label: "美元" },
  { value: "PieChart", icon: PieChartOutlined, label: "饼图" },
  { value: "LineChart", icon: AreaChartOutlined, label: "折线图" },
  { value: "BarChart", icon: BarChartOutlined, label: "柱状图" },
  { value: "Calendar", icon: CalendarOutlined, label: "日历" },
  { value: "Timer", icon: FieldTimeOutlined, label: "计时器" },
  { value: "Bell", icon: BellOutlined, label: "铃铛" },
  { value: "Volume2", icon: SoundOutlined, label: "音量" },
  { value: "Mic", icon: CustomerServiceOutlined, label: "麦克风" },
  { value: "Video", icon: VideoCameraOutlined, label: "视频" },
  { value: "Image", icon: PictureOutlined, label: "图片" },
  { value: "Film", icon: PlayCircleOutlined, label: "电影" },
  { value: "Music", icon: MusicNoteOutlined, label: "音乐" },
  { value: "Radio", icon: RadiusSettingOutlined, label: "收音机" },
  { value: "Tv", icon: DesktopOutlined, label: "电视" },
  { value: "Rss", icon: RssOutlined, label: "RSS" },
  { value: "Newspaper", icon: ReadOutlined, label: "新闻" },
  { value: "Book", icon: EditOutlined, label: "书籍" },
  { value: "GraduationCap", icon: BulbOutlined, label: "毕业帽" },
  { value: "Award", icon: MedalOutlined, label: "奖项" },
  { value: "Trophy", icon: TrophyOutlined, label: "奖杯" },
  { value: "Medal", icon: MedalOutlined, label: "奖牌" },
  { value: "Gift", icon: RedEnvelopeOutlined, label: "礼物" },
  { value: "Sparkles", icon: FireOutlined, label: "闪光" },
  { value: "Flame", icon: FireOutlined, label: "火焰" },
  { value: "Sun", icon: SunOutlined, label: "太阳" },
  { value: "Moon", icon: MoonOutlined, label: "月亮" },
  { value: "CloudRain", icon: CloudRainOutlined, label: "雨云" },
  { value: "Snowflake", icon: SnowflakeOutlined, label: "雪花" },
  { value: "Umbrella", icon: UmbrellaOutlined, label: "雨伞" },
  { value: "Thermometer", icon: DashboardOutlined, label: "温度计" },
  { value: "Wind", icon: WindPowerOutlined, label: "风" },
  { value: "Eye", icon: EyeOutlined, label: "眼睛" },
  { value: "Search", icon: SearchOutlined, label: "搜索" },
  { value: "Filter", icon: FilterOutlined, label: "过滤" },
  { value: "RefreshCw", icon: ReloadOutlined, label: "刷新" },
  { value: "Download", icon: DownloadOutlined, label: "下载" },
  { value: "Upload", icon: UploadOutlined, label: "上传" },
  { value: "Share", icon: ShareAltOutlined, label: "分享" },
  { value: "Copy", icon: CopyOutlined, label: "复制" },
  { value: "Scissors", icon: ScissorOutlined, label: "剪刀" },
  { value: "Paperclip", icon: PaperClipOutlined, label: "回形针" },
  { value: "Link2", icon: LinkOutlined, label: "链接" },
  { value: "Lock", icon: LockOutlined, label: "锁定" },
  { value: "Unlock", icon: UnlockOutlined, label: "解锁" },
  { value: "UserCheck", icon: UserSwitchOutlined, label: "用户确认" },
  { value: "UserPlus", icon: UserAddOutlined, label: "添加用户" },
  { value: "Crown", icon: CrownOutlined, label: "皇冠" },
  { value: "Briefcase", icon: ContainerOutlined, label: "公文包" },
  { value: "Building", icon: BuildingOutlined, label: "建筑" },
  { value: "Factory", icon: BankOutlined, label: "工厂" },
  { value: "Store", icon: ShopOutlined, label: "商店" },
  { value: "Warehouse", icon: GoldOutlined, label: "仓库" },
  { value: "MapPin", icon: PushpinOutlined, label: "地图标记" },
  { value: "Car", icon: CarOutlined, label: "汽车" },
  { value: "Bus", icon: TrademarkCircleOutlined, label: "公交车" },
  { value: "Train", icon: ProjectOutlined, label: "火车" },
  { value: "Plane", icon: RocketOutlined, label: "飞机" },
  { value: "Ship", icon: ShipOutlined, label: "轮船" },
  { value: "Bike", icon: BikeOutlined, label: "自行车" },
  { value: "Fuel", icon: ExperimentOutlined, label: "燃料" },
  { value: "Battery", icon: BatteryTwoTone, label: "电池" },
  { value: "Plug", icon: PlugOneOutlined, label: "插头" },
  { value: "Power", icon: PoweroffOutlined, label: "电源" },
  { value: "Scan", icon: ScanOutlined, label: "扫描" },
  { value: "QrCode", icon: QrcodeOutlined, label: "二维码" },
  { value: "Barcode", icon: BarcodeOutlined, label: "条形码" },
  { value: "Hash", icon: NumberOutlined, label: "井号" },
  { value: "AtSign", icon: AtSignOutlined, label: "@符号" },
  { value: "Percent", icon: PercentageOutlined, label: "百分号" },
  { value: "Fingerprint", icon: SafetyCertificateOutlined, label: "指纹" },
  { value: "Palette", icon: BgColorsOutlined, label: "调色板" },
  { value: "Brush", icon: HighlightOutlined, label: "画笔" },
  { value: "Pen", icon: EditTwoToneOutlined, label: "钢笔" },
  { value: "PenTool", icon: FormOutlined, label: "钢笔工具" },
  { value: "Eraser", icon: DeleteOutlined, label: "橡皮擦" },
  { value: "Ruler", icon: LineOutlined, label: "尺子" },
  { value: "Type", icon: FontSizeOutlined, label: "文字" },
  { value: "Bold", icon: BoldOutlined, label: "粗体" },
  { value: "Italic", icon: ItalicOutlined, label: "斜体" },
  { value: "Underline", icon: UnderlineOutlined, label: "下划线" },
  { value: "Quote", icon: MessageOutlined, label: "引用" },
  { value: "List", icon: OrderedListOutlined, label: "列表" },
  { value: "Layout", icon: LayoutOutlined, label: "布局" },
  { value: "LayoutGrid", icon: TableOutlined, label: "网格布局" },
  { value: "Columns", icon: ColumnWidthOutlined, label: "列" },
  { value: "Square", icon: BorderInnerOutlined, label: "正方形" },
  { value: "Circle", icon: RadiusUprightOutlined, label: "圆形" },
  { value: "Triangle", icon: CaretUpOutlined, label: "三角形" },
  { value: "Hexagon", icon: StopOutlined, label: "六边形" },
  { value: "Diamond", icon: DiamondOutlined, label: "菱形" },
  { value: "Shapes", icon: BlockOutlined, label: "形状" },
  { value: "Puzzle", icon: PuzzleOutlined, label: "拼图" },
  { value: "Component", icon: DeploymentUnitOutlined, label: "组件" },
  { value: "Workflow", icon: WorkflowOutlined, label: "工作流" },
  { value: "GitBranch", icon: BranchesOutlined, label: "Git分支" },
  { value: "Github", icon: GithubOutlined, label: "GitHub" },
  { value: "Chrome", icon: ChromeOutlined, label: "Chrome" },
  { value: "Firefox", icon: FirefoxOutlined, label: "Firefox" },
  { value: "Bluetooth", icon: BluetoothOutlined, label: "蓝牙" },
  { value: "Usb", icon: UsbOutlined, label: "USB" },
  { value: "Disc", icon: CustomerServiceFilled, label: "光盘" },
  { value: "Folder", icon: FolderOutlined, label: "文件夹" },
  { value: "File", icon: FileOutlined, label: "文件" },
  { value: "Archive", icon: FileZipOutlined, label: "归档" },
  { value: "Inbox", icon: MailInboxOutlined, label: "收件箱" },
  { value: "Send", icon: SendOutlined, label: "发送" },
  { value: "Reply", icon: RollbackOutlined, label: "回复" },
  { value: "Forward", icon: ForwardOutlined, label: "转发" },
  { value: "Trash", icon: DeleteOutlined, label: "垃圾桶" },
  // 新增的图标
  { value: "Api", icon: ApiOutlined, label: "API接口" },
  { value: "AppstoreAdd", icon: AppstoreAddOutlined, label: "应用市场" },
  { value: "Apartment", icon: ApartmentOutlined, label: "公寓" },
  { value: "Team", icon: TeamOutlined, label: "团队" },
  { value: "UsergroupAdd", icon: UsergroupAddOutlined, label: "用户组" },
  { value: "NodeIndex", icon: NodeIndexOutlined, label: "节点" },
  { value: "Cluster", icon: ClusterOutlined, label: "集群" },
  { value: "SecurityScan", icon: SecurityScanOutlined, label: "安全扫描" },
  { value: "Audit", icon: AuditOutlined, label: "审计" },
  { value: "Control", icon: ControlOutlined, label: "控制" },
  { value: "Function", icon: FunctionOutlined, label: "函数" },
  { value: "Bug", icon: BugOutlined, label: "错误" },
  { value: "Tool", icon: ToolOutlined, label: "工具" },
  { value: "Warning", icon: WarningOutlined, label: "警告" },
  { value: "Info", icon: InfoCircleOutlined, label: "信息" },
  { value: "Question", icon: QuestionCircleOutlined, label: "问号" },
  { value: "Smile", icon: SmileOutlined, label: "笑脸" },
  { value: "Frown", icon: FrownOutlined, label: "哭脸" },
  { value: "Meh", icon: MehOutlined, label: "无表情" },
  { value: "Interaction", icon: InteractionOutlined, label: "交互" },
  { value: "Notification", icon: NotificationOutlined, label: "通知" },
  { value: "Alert", icon: AlertOutlined, label: "提醒" },
];

// 颜色选项
export const colorOptions: ColorOption[] = [
  { value: "bg-blue-500", label: "蓝色", color: "#3b82f6" },
  { value: "bg-green-500", label: "绿色", color: "#10b981" },
  { value: "bg-purple-500", label: "紫色", color: "#8b5cf6" },
  { value: "bg-orange-500", label: "橙色", color: "#f97316" },
  { value: "bg-red-500", label: "红色", color: "#ef4444" },
  { value: "bg-indigo-500", label: "靛蓝", color: "#6366f1" },
  { value: "bg-pink-500", label: "粉色", color: "#ec4899" },
  { value: "bg-teal-500", label: "青色", color: "#14b8a6" },
  { value: "bg-yellow-500", label: "黄色", color: "#eab308" },
  { value: "bg-cyan-500", label: "青蓝", color: "#06b6d4" },
  { value: "bg-emerald-500", label: "翠绿", color: "#10b981" },
  { value: "bg-violet-500", label: "紫罗兰", color: "#8b5cf6" },
  { value: "bg-rose-500", label: "玫瑰", color: "#f43f5e" },
  { value: "bg-amber-500", label: "琥珀", color: "#f59e0b" },
  { value: "bg-lime-500", label: "酸橙", color: "#84cc16" },
  { value: "bg-sky-500", label: "天空蓝", color: "#0ea5e9" },
  { value: "bg-slate-500", label: "石板灰", color: "#64748b" },
  { value: "bg-gray-500", label: "灰色", color: "#6b7280" },
  { value: "bg-zinc-500", label: "锌色", color: "#71717a" },
  { value: "bg-neutral-500", label: "中性", color: "#737373" },
];

// URL类型选项
export const urlTypeOptions: UrlTypeOption[] = [
  // { 
  //   value: "internal_terminal", 
  //   label: "终端内跳转", 
  //   description: "使用当前域名拼接URL并在浏览器中打开" 
  // },
  { 
    value: "internal", 
    label: "URL跳转", 
    description: "直接在浏览器新标签页中打开链接" 
  },
  { 
    value: "terminal", 
    label: "终端命令", 
    description: "使用windlocal协议执行的终端命令" 
  },
];

// 菜单项配置
export const menuItems: MenuItem[] = [
  { id: "dashboard", label: "工作台", icon: HomeOutlined },
  { id: "platforms", label: "管理平台", icon: SettingOutlined },
  { id: "services", label: "技术服务", icon: DatabaseOutlined },
  { id: "users", label: "用户管理", icon: UserSwitchOutlined },
  { id: "docs", label: "帮助中心", icon: BookFilled },
  { id: "operation-logs", label: "操作日志", icon: FileTextOutlined },
  { id: "ai-agent", label: "Agent", icon: FireOutlined },
  { id: "coming-soon", label: "敬请期待", icon: ClockCircleOutlined },
];
