// 图标数据
import {
  Settings,
  Users,
  Database,
  Key,
  Mail,
  FileText,
  BarChart3,
  Cloud,
  Shield,
  Zap,
  Globe,
  Code,
  Monitor,
  Server,
  Smartphone,
  Laptop,
  HardDrive,
  Wifi,
  Camera,
  Headphones,
  Gamepad2,
  Printer,
  Activity,
  AlertCircle,
  CheckCircle,
  Clock,
  Star,
  Heart,
  Bookmark,
  Flag,
  Target,
  Compass,
  Map,
  Navigation,
  Layers,
  Grid,
  Box,
  Package,
  Truck,
  ShoppingCart,
  CreditCard,
  DollarSign,
  PieChart,
  LineChart,
  BarChart,
  Calendar,
  Timer,
  Bell,
  Volume2,
  Mic,
  Video,
  Image,
  Film,
  Music,
  Radio,
  Tv,
  Rss,
  Newspaper,
  Book,
  GraduationCap,
  Award,
  Trophy,
  Medal,
  Gift,
  Sparkles,
  Flame,
  Sun,
  Moon,
  CloudRain,
  Snowflake,
  Umbrella,
  Thermometer,
  Wind,
  Eye,
  Search,
  Filter,
  RefreshCw,
  Download,
  Upload,
  Share,
  Copy,
  Scissors,
  Paperclip,
  Link2,
  Lock,
  Unlock,
  UserCheck,
  UserPlus,
  Crown,
  Briefcase,
  Building,
  Factory,
  Store,
  Warehouse,
  MapPin,
  Car,
  Bus,
  Train,
  Plane,
  Ship,
  Bike,
  Fuel,
  Battery,
  Plug,
  Power,
  Scan,
  QrCode,
  Barcode,
  Hash,
  AtSign,
  Percent,
  Fingerprint,
  Palette,
  Brush,
  Pen,
  PenTool,
  Eraser,
  Ruler,
  Type,
  Bold,
  Italic,
  Underline,
  Quote,
  List,
  Layout,
  LayoutGrid,
  Columns,
  Square,
  Circle,
  Triangle,
  Hexagon,
  Diamond,
  Shapes,
  Puzzle,
  Component,
  Workflow,
  GitBranch,
  Github,
  Chrome,
  ChromeIcon as Firefox,
  Bluetooth,
  Usb,
  Disc,
  Folder,
  File,
  Archive,
  Inbox,
  Send,
  Reply,
  Forward,
  Trash,
  Home,
  BookOpen,
  GripVertical,
} from "lucide-react";

import { IconOption, ColorOption, MenuItem, UrlTypeOption } from "./types";

// 头像图标选项
export const iconOptions: IconOption[] = [
  { value: "Settings", icon: Settings, label: "设置" },
  { value: "Users", icon: Users, label: "用户" },
  { value: "Database", icon: Database, label: "数据库" },
  { value: "Key", icon: Key, label: "密钥" },
  { value: "Mail", icon: Mail, label: "邮件" },
  { value: "FileText", icon: FileText, label: "文档" },
  { value: "BarChart3", icon: BarChart3, label: "图表" },
  { value: "Cloud", icon: Cloud, label: "云服务" },
  { value: "Shield", icon: Shield, label: "安全" },
  { value: "Zap", icon: Zap, label: "闪电" },
  { value: "Globe", icon: Globe, label: "全球" },
  { value: "Code", icon: Code, label: "代码" },
  { value: "Monitor", icon: Monitor, label: "监控" },
  { value: "Server", icon: Server, label: "服务器" },
  { value: "Smartphone", icon: Smartphone, label: "手机" },
  { value: "Laptop", icon: Laptop, label: "笔记本" },
  { value: "HardDrive", icon: HardDrive, label: "硬盘" },
  { value: "Wifi", icon: Wifi, label: "网络" },
  { value: "Camera", icon: Camera, label: "相机" },
  { value: "Headphones", icon: Headphones, label: "耳机" },
  { value: "Gamepad2", icon: Gamepad2, label: "游戏" },
  { value: "Printer", icon: Printer, label: "打印机" },
  { value: "Activity", icon: Activity, label: "活动" },
  { value: "AlertCircle", icon: AlertCircle, label: "警告" },
  { value: "CheckCircle", icon: CheckCircle, label: "完成" },
  { value: "Clock", icon: Clock, label: "时钟" },
  { value: "Star", icon: Star, label: "星星" },
  { value: "Heart", icon: Heart, label: "心形" },
  { value: "Bookmark", icon: Bookmark, label: "书签" },
  { value: "Flag", icon: Flag, label: "旗帜" },
  { value: "Target", icon: Target, label: "目标" },
  { value: "Compass", icon: Compass, label: "指南针" },
  { value: "Map", icon: Map, label: "地图" },
  { value: "Navigation", icon: Navigation, label: "导航" },
  { value: "Layers", icon: Layers, label: "图层" },
  { value: "Grid", icon: Grid, label: "网格" },
  { value: "Box", icon: Box, label: "盒子" },
  { value: "Package", icon: Package, label: "包裹" },
  { value: "Truck", icon: Truck, label: "卡车" },
  { value: "ShoppingCart", icon: ShoppingCart, label: "购物车" },
  { value: "CreditCard", icon: CreditCard, label: "信用卡" },
  { value: "DollarSign", icon: DollarSign, label: "美元" },
  { value: "PieChart", icon: PieChart, label: "饼图" },
  { value: "LineChart", icon: LineChart, label: "折线图" },
  { value: "BarChart", icon: BarChart, label: "柱状图" },
  { value: "Calendar", icon: Calendar, label: "日历" },
  { value: "Timer", icon: Timer, label: "计时器" },
  { value: "Bell", icon: Bell, label: "铃铛" },
  { value: "Volume2", icon: Volume2, label: "音量" },
  { value: "Mic", icon: Mic, label: "麦克风" },
  { value: "Video", icon: Video, label: "视频" },
  { value: "Image", icon: Image, label: "图片" },
  { value: "Film", icon: Film, label: "电影" },
  { value: "Music", icon: Music, label: "音乐" },
  { value: "Radio", icon: Radio, label: "收音机" },
  { value: "Tv", icon: Tv, label: "电视" },
  { value: "Rss", icon: Rss, label: "RSS" },
  { value: "Newspaper", icon: Newspaper, label: "新闻" },
  { value: "Book", icon: Book, label: "书籍" },
  { value: "GraduationCap", icon: GraduationCap, label: "毕业帽" },
  { value: "Award", icon: Award, label: "奖项" },
  { value: "Trophy", icon: Trophy, label: "奖杯" },
  { value: "Medal", icon: Medal, label: "奖牌" },
  { value: "Gift", icon: Gift, label: "礼物" },
  { value: "Sparkles", icon: Sparkles, label: "闪光" },
  { value: "Flame", icon: Flame, label: "火焰" },
  { value: "Sun", icon: Sun, label: "太阳" },
  { value: "Moon", icon: Moon, label: "月亮" },
  { value: "CloudRain", icon: CloudRain, label: "雨云" },
  { value: "Snowflake", icon: Snowflake, label: "雪花" },
  { value: "Umbrella", icon: Umbrella, label: "雨伞" },
  { value: "Thermometer", icon: Thermometer, label: "温度计" },
  { value: "Wind", icon: Wind, label: "风" },
  { value: "Eye", icon: Eye, label: "眼睛" },
  { value: "Search", icon: Search, label: "搜索" },
  { value: "Filter", icon: Filter, label: "过滤" },
  { value: "RefreshCw", icon: RefreshCw, label: "刷新" },
  { value: "Download", icon: Download, label: "下载" },
  { value: "Upload", icon: Upload, label: "上传" },
  { value: "Share", icon: Share, label: "分享" },
  { value: "Copy", icon: Copy, label: "复制" },
  { value: "Scissors", icon: Scissors, label: "剪刀" },
  { value: "Paperclip", icon: Paperclip, label: "回形针" },
  { value: "Link2", icon: Link2, label: "链接" },
  { value: "Lock", icon: Lock, label: "锁定" },
  { value: "Unlock", icon: Unlock, label: "解锁" },
  { value: "UserCheck", icon: UserCheck, label: "用户确认" },
  { value: "UserPlus", icon: UserPlus, label: "添加用户" },
  { value: "Crown", icon: Crown, label: "皇冠" },
  { value: "Briefcase", icon: Briefcase, label: "公文包" },
  { value: "Building", icon: Building, label: "建筑" },
  { value: "Factory", icon: Factory, label: "工厂" },
  { value: "Store", icon: Store, label: "商店" },
  { value: "Warehouse", icon: Warehouse, label: "仓库" },
  { value: "MapPin", icon: MapPin, label: "地图标记" },
  { value: "Car", icon: Car, label: "汽车" },
  { value: "Bus", icon: Bus, label: "公交车" },
  { value: "Train", icon: Train, label: "火车" },
  { value: "Plane", icon: Plane, label: "飞机" },
  { value: "Ship", icon: Ship, label: "轮船" },
  { value: "Bike", icon: Bike, label: "自行车" },
  { value: "Fuel", icon: Fuel, label: "燃料" },
  { value: "Battery", icon: Battery, label: "电池" },
  { value: "Plug", icon: Plug, label: "插头" },
  { value: "Power", icon: Power, label: "电源" },
  { value: "Scan", icon: Scan, label: "扫描" },
  { value: "QrCode", icon: QrCode, label: "二维码" },
  { value: "Barcode", icon: Barcode, label: "条形码" },
  { value: "Hash", icon: Hash, label: "井号" },
  { value: "AtSign", icon: AtSign, label: "@符号" },
  { value: "Percent", icon: Percent, label: "百分号" },
  { value: "Fingerprint", icon: Fingerprint, label: "指纹" },
  { value: "Palette", icon: Palette, label: "调色板" },
  { value: "Brush", icon: Brush, label: "画笔" },
  { value: "Pen", icon: Pen, label: "钢笔" },
  { value: "PenTool", icon: PenTool, label: "钢笔工具" },
  { value: "Eraser", icon: Eraser, label: "橡皮擦" },
  { value: "Ruler", icon: Ruler, label: "尺子" },
  { value: "Type", icon: Type, label: "文字" },
  { value: "Bold", icon: Bold, label: "粗体" },
  { value: "Italic", icon: Italic, label: "斜体" },
  { value: "Underline", icon: Underline, label: "下划线" },
  { value: "Quote", icon: Quote, label: "引用" },
  { value: "List", icon: List, label: "列表" },
  { value: "Layout", icon: Layout, label: "布局" },
  { value: "LayoutGrid", icon: LayoutGrid, label: "网格布局" },
  { value: "Columns", icon: Columns, label: "列" },
  { value: "Square", icon: Square, label: "正方形" },
  { value: "Circle", icon: Circle, label: "圆形" },
  { value: "Triangle", icon: Triangle, label: "三角形" },
  { value: "Hexagon", icon: Hexagon, label: "六边形" },
  { value: "Diamond", icon: Diamond, label: "菱形" },
  { value: "Shapes", icon: Shapes, label: "形状" },
  { value: "Puzzle", icon: Puzzle, label: "拼图" },
  { value: "Component", icon: Component, label: "组件" },
  { value: "Workflow", icon: Workflow, label: "工作流" },
  { value: "GitBranch", icon: GitBranch, label: "Git分支" },
  { value: "Github", icon: Github, label: "GitHub" },
  { value: "Chrome", icon: Chrome, label: "Chrome" },
  { value: "Firefox", icon: Firefox, label: "Firefox" },
  { value: "Bluetooth", icon: Bluetooth, label: "蓝牙" },
  { value: "Usb", icon: Usb, label: "USB" },
  { value: "Disc", icon: Disc, label: "光盘" },
  { value: "Folder", icon: Folder, label: "文件夹" },
  { value: "File", icon: File, label: "文件" },
  { value: "Archive", icon: Archive, label: "归档" },
  { value: "Inbox", icon: Inbox, label: "收件箱" },
  { value: "Send", icon: Send, label: "发送" },
  { value: "Reply", icon: Reply, label: "回复" },
  { value: "Forward", icon: Forward, label: "转发" },
  { value: "Trash", icon: Trash, label: "垃圾桶" },
];

// 颜色选项
export const colorOptions: ColorOption[] = [
  { value: "bg-blue-500", label: "蓝色", color: "#3b82f6" },
  { value: "bg-green-500", label: "绿色", color: "#10b981" },
  { value: "bg-purple-500", label: "紫色", color: "#8b5cf6" },
  { value: "bg-orange-500", label: "橙色", color: "#f97316" },
  { value: "bg-red-500", label: "红色", color: "#ef4444" },
  { value: "bg-indigo-500", label: "靛蓝", color: "#6366f1" },
  { value: "bg-pink-500", label: "粉色", color: "#ec4899" },
  { value: "bg-teal-500", label: "青色", color: "#14b8a6" },
  { value: "bg-yellow-500", label: "黄色", color: "#eab308" },
  { value: "bg-cyan-500", label: "青蓝", color: "#06b6d4" },
  { value: "bg-emerald-500", label: "翠绿", color: "#10b981" },
  { value: "bg-violet-500", label: "紫罗兰", color: "#8b5cf6" },
  { value: "bg-rose-500", label: "玫瑰", color: "#f43f5e" },
  { value: "bg-amber-500", label: "琥珀", color: "#f59e0b" },
  { value: "bg-lime-500", label: "酸橙", color: "#84cc16" },
  { value: "bg-sky-500", label: "天空蓝", color: "#0ea5e9" },
  { value: "bg-slate-500", label: "石板灰", color: "#64748b" },
  { value: "bg-gray-500", label: "灰色", color: "#6b7280" },
  { value: "bg-zinc-500", label: "锌色", color: "#71717a" },
  { value: "bg-neutral-500", label: "中性", color: "#737373" },
];

// URL类型选项
export const urlTypeOptions: UrlTypeOption[] = [
  { 
    value: "internal", 
    label: "内网链接", 
    description: "内网地址，在浏览器中打开" 
  },
  { 
    value: "terminal", 
    label: "终端命令", 
    description: "使用windlocal协议执行的终端命令" 
  },
];

// 菜单项配置
export const menuItems: MenuItem[] = [
  { id: "dashboard", label: "工作台", icon: Home },
  { id: "platforms", label: "管理平台", icon: Settings },
  { id: "services", label: "技术服务", icon: Database },
  { id: "users", label: "用户管理", icon: UserCheck },
  { id: "docs", label: "帮助中心", icon: BookOpen },
  { id: "operation-logs", label: "操作日志", icon: FileText },
];
